// <auto-generated />
using System;
using LumStoreAPI.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LumStoreAPI.Infrastructure.Migrations
{
    [DbContext(typeof(LumStoreContext))]
    [Migration("20260331110716_Initital")]
    partial class Initital
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LumStoreAPI.Core.Entities.DocumentEngine.DocumentLinkedNode", b =>
                {
                    b.Property<int>("Ancestor")
                        .HasColumnType("int");

                    b.Property<int>("Descendant")
                        .HasColumnType("int");

                    b.Property<int>("Depth")
                        .HasColumnType("int");

                    b.HasKey("Ancestor", "Descendant", "Depth");

                    b.HasIndex("Descendant");

                    b.ToTable("DocumentLinkedNodes");
                });

            modelBuilder.Entity("LumStoreAPI.Core.Entities.DocumentEngine.DocumentNode", b =>
                {
                    b.Property<int>("NodeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NodeID"));

                    b.Property<string>("NodeAlias")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("NodeOrder")
                        .HasColumnType("int");

                    b.Property<int?>("ParentNodeID")
                        .HasColumnType("int");

                    b.HasKey("NodeID");

                    b.HasIndex("NodeOrder", "ParentNodeID");

                    b.HasIndex("ParentNodeID", "NodeAlias")
                        .IsUnique()
                        .HasFilter("[ParentNodeID] IS NOT NULL");

                    b.ToTable("DocumentNodes");
                });

            modelBuilder.Entity("LumStoreAPI.Core.Entities.DocumentEngine.DocumentPage", b =>
                {
                    b.Property<int>("PageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PageID"));

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("NodeID")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("PublishedFrom")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("PublishedTo")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("RequireAuthentication")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("PageID");

                    b.HasIndex("NodeID");

                    b.ToTable("DocumentPages");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("LumStoreAPI.Core.Entities.Pages.ProductVariant", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemID"));

                    b.Property<string>("Color")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Images")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("UPC")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("VariantName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ItemID");

                    b.HasIndex("ProductID");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.ToTable("ProductVariants");
                });

            modelBuilder.Entity("LumStoreAPI.Core.Entities.Systems.EmailQueue", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemID"));

                    b.Property<string>("Attachments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EmailBcc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailBody")
                        .IsRequired()
                        .HasMaxLength(-1)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailCc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailFrom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmailStatus")
                        .HasColumnType("int");

                    b.Property<string>("EmailSubject")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmailTo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset?>("NextRetryTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ItemID");

                    b.HasIndex("EmailSubject");

                    b.HasIndex("EmailTo");

                    b.ToTable("EmailQueues");
                });

            modelBuilder.Entity("LumStoreAPI.Core.Entities.Systems.EventLog", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemID"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EventCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EventDescription")
                        .IsRequired()
                        .HasMaxLength(-1)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EventLogType")
                        .HasColumnType("int");

                    b.Property<string>("EventName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EventSource")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EventUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ServerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ItemID");

                    b.HasIndex("EventCode");

                    b.HasIndex("EventName");

                    b.HasIndex("EventSource");

                    b.HasIndex("IPAddress");

                    b.HasIndex("UserID");

                    b.ToTable("EventLogs");
                });

            modelBuilder.Entity("LumStoreAPI.Core.Entities.Systems.MediaLibrary", b =>
                {
                    b.Property<Guid>("FileID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Extension")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("FileID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("FileName")
                        .IsUnique();

                    b.ToTable("MediaLibraries");
                });

            modelBuilder.Entity("LumStoreAPI.Core.Entities.Systems.MediaLibraryCategory", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FolderName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("CategoryID");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.HasIndex("FolderName")
                        .IsUnique();

                    b.ToTable("MediaLibraryCategories");
                });

            modelBuilder.Entity("LumStoreAPI.Core.Entities.Systems.SettingKeyValue", b =>
                {
                    b.Property<string>("SettingCode")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("SettingName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("SettingCode");

                    b.ToTable("SettingKeyValues");
                });

            modelBuilder.Entity("LumStoreAPI.Core.Entities.Systems.User", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemID"));

                    b.Property<string>("Avatar")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("TimeActionCode")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("TimeLocked")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("UserLevel")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VerifyCode")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.HasKey("ItemID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LumStoreAPI.Core.Entities.Systems.UserToken", b =>
                {
                    b.Property<Guid>("TokenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ValidTo")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("TokenID");

                    b.HasIndex("UserID");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("LumStoreAPI.Core.Entities.Pages.HomePage", b =>
                {
                    b.HasBaseType("LumStoreAPI.Core.Entities.DocumentEngine.DocumentPage");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PageTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.ToTable("HomePages");
                });

            modelBuilder.Entity("LumStoreAPI.Core.Entities.Pages.Product", b =>
                {
                    b.HasBaseType("LumStoreAPI.Core.Entities.DocumentEngine.DocumentPage");

                    b.Property<string>("Description")
                        .HasMaxLength(-1)
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.PrimitiveCollection<string>("Images")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAlcoholic")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFoldable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFragile")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHazmat")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNeedBox")
                        .HasColumnType("bit");

                    b.Property<double>("Length")
                        .HasColumnType("float");

                    b.Property<int>("ProductGroup")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProductType")
                        .HasColumnType("int");

                    b.Property<int>("ShiprelayID")
                        .HasColumnType("int");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.Property<double>("Width")
                        .HasColumnType("float");

                    b.HasIndex("ProductName");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("LumStoreAPI.Core.Entities.Pages.ProductCategory", b =>
                {
                    b.HasBaseType("LumStoreAPI.Core.Entities.DocumentEngine.DocumentPage");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.ToTable("ProductCategories");
                });

            modelBuilder.Entity("LumStoreAPI.Core.Entities.DocumentEngine.DocumentLinkedNode", b =>
                {
                    b.HasOne("LumStoreAPI.Core.Entities.DocumentEngine.DocumentNode", "AncestorNode")
                        .WithMany("AncestorNodes")
                        .HasForeignKey("Ancestor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LumStoreAPI.Core.Entities.DocumentEngine.DocumentNode", "DescendantNode")
                        .WithMany("DescendantNodes")
                        .HasForeignKey("Descendant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AncestorNode");

                    b.Navigation("DescendantNode");
                });

            modelBuilder.Entity("LumStoreAPI.Core.Entities.DocumentEngine.DocumentNode", b =>
                {
                    b.HasOne("LumStoreAPI.Core.Entities.DocumentEngine.DocumentNode", "Parent")
                        .WithMany("Childrens")
                        .HasForeignKey("ParentNodeID");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("LumStoreAPI.Core.Entities.DocumentEngine.DocumentPage", b =>
                {
                    b.HasOne("LumStoreAPI.Core.Entities.DocumentEngine.DocumentNode", "Node")
                        .WithMany("Properties")
                        .HasForeignKey("NodeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");
                });

            modelBuilder.Entity("LumStoreAPI.Core.Entities.Pages.ProductVariant", b =>
                {
                    b.HasOne("LumStoreAPI.Core.Entities.Pages.Product", "Product")
                        .WithMany("ProductVariants")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("LumStoreAPI.Core.Entities.Systems.EventLog", b =>
                {
                    b.HasOne("LumStoreAPI.Core.Entities.Systems.User", "User")
                        .WithMany("EventLogs")
                        .HasForeignKey("UserID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LumStoreAPI.Core.Entities.Systems.MediaLibrary", b =>
                {
                    b.HasOne("LumStoreAPI.Core.Entities.Systems.MediaLibraryCategory", "MediaLibraryCategory")
                        .WithMany("MediaLibraries")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaLibraryCategory");
                });

            modelBuilder.Entity("LumStoreAPI.Core.Entities.Systems.UserToken", b =>
                {
                    b.HasOne("LumStoreAPI.Core.Entities.Systems.User", "User")
                        .WithMany("UserTokens")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LumStoreAPI.Core.Entities.Pages.HomePage", b =>
                {
                    b.HasOne("LumStoreAPI.Core.Entities.DocumentEngine.DocumentPage", null)
                        .WithOne()
                        .HasForeignKey("LumStoreAPI.Core.Entities.Pages.HomePage", "PageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LumStoreAPI.Core.Entities.Pages.Product", b =>
                {
                    b.HasOne("LumStoreAPI.Core.Entities.DocumentEngine.DocumentPage", null)
                        .WithOne()
                        .HasForeignKey("LumStoreAPI.Core.Entities.Pages.Product", "PageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LumStoreAPI.Core.Entities.Pages.ProductCategory", b =>
                {
                    b.HasOne("LumStoreAPI.Core.Entities.DocumentEngine.DocumentPage", null)
                        .WithOne()
                        .HasForeignKey("LumStoreAPI.Core.Entities.Pages.ProductCategory", "PageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LumStoreAPI.Core.Entities.DocumentEngine.DocumentNode", b =>
                {
                    b.Navigation("AncestorNodes");

                    b.Navigation("Childrens");

                    b.Navigation("DescendantNodes");

                    b.Navigation("Properties");
                });

            modelBuilder.Entity("LumStoreAPI.Core.Entities.Systems.MediaLibraryCategory", b =>
                {
                    b.Navigation("MediaLibraries");
                });

            modelBuilder.Entity("LumStoreAPI.Core.Entities.Systems.User", b =>
                {
                    b.Navigation("EventLogs");

                    b.Navigation("UserTokens");
                });

            modelBuilder.Entity("LumStoreAPI.Core.Entities.Pages.Product", b =>
                {
                    b.Navigation("ProductVariants");
                });
#pragma warning restore 612, 618
        }
    }
}
