// <auto-generated />
using System;
using LumStoreAPI.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LumStoreAPI.Infrastructure.Migrations
{
    [DbContext(typeof(LumStoreContext))]
    [Migration("20260304173726_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LumStoreAPI.Core.Entities.DocumentEngine.DocumentLinkedNode", b =>
                {
                    b.Property<int>("Ancestor")
                        .HasColumnType("int");

                    b.Property<int>("Descendant")
                        .HasColumnType("int");

                    b.Property<int>("Depth")
                        .HasColumnType("int");

                    b.HasKey("Ancestor", "Descendant", "Depth");

                    b.HasIndex("Descendant");

                    b.ToTable("DocumentLinkedNodes");
                });

            modelBuilder.Entity("LumStoreAPI.Core.Entities.DocumentEngine.DocumentNode", b =>
                {
                    b.Property<int>("NodeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NodeID"));

                    b.Property<string>("NodeAlias")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("NodeOrder")
                        .HasColumnType("int");

                    b.Property<int?>("ParentNodeID")
                        .HasColumnType("int");

                    b.HasKey("NodeID");

                    b.HasIndex("NodeOrder", "ParentNodeID");

                    b.HasIndex("ParentNodeID", "NodeAlias")
                        .IsUnique()
                        .HasFilter("[ParentNodeID] IS NOT NULL");

                    b.ToTable("DocumentNodes");
                });

            modelBuilder.Entity("LumStoreAPI.Core.Entities.DocumentEngine.DocumentPage", b =>
                {
                    b.Property<int>("PageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PageID"));

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ForeignKeyID")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("NodeID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PublishedFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PublishedTo")
                        .HasColumnType("datetime2");

                    b.Property<bool>("RequireAuthentication")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PageID");

                    b.HasIndex("NodeID");

                    b.ToTable("DocumentPages");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("LumStoreAPI.Core.Entities.Systems.EmailQueue", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemID"));

                    b.Property<string>("Attachments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailBcc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailBody")
                        .IsRequired()
                        .HasMaxLength(-1)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailCc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailFrom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmailStatus")
                        .HasColumnType("int");

                    b.Property<string>("EmailSubject")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmailTo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ItemID");

                    b.HasIndex("EmailSubject");

                    b.HasIndex("EmailTo");

                    b.ToTable("EmailQueues");
                });

            modelBuilder.Entity("LumStoreAPI.Core.Entities.Systems.EventLog", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EventDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EventLogType")
                        .HasColumnType("int");

                    b.Property<string>("EventName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EventSource")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EventUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPAddress")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ServerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ItemID");

                    b.HasIndex("EventCode");

                    b.HasIndex("EventName");

                    b.HasIndex("EventSource");

                    b.HasIndex("IPAddress");

                    b.ToTable("EventLogs");
                });

            modelBuilder.Entity("LumStoreAPI.Core.Entities.Systems.MediaLibrary", b =>
                {
                    b.Property<Guid>("FileID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Extension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("FileID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("FileName")
                        .IsUnique();

                    b.ToTable("MediaLibraries");
                });

            modelBuilder.Entity("LumStoreAPI.Core.Entities.Systems.MediaLibraryCategory", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FolderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CategoryID");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.HasIndex("FolderName")
                        .IsUnique();

                    b.ToTable("MediaLibraryCategories");
                });

            modelBuilder.Entity("LumStoreAPI.Core.Entities.Systems.SettingKeyValue", b =>
                {
                    b.Property<string>("SettingCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SettingName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SettingCode");

                    b.ToTable("SettingKeyValues");
                });

            modelBuilder.Entity("LumStoreAPI.Core.Entities.HomePage", b =>
                {
                    b.HasBaseType("LumStoreAPI.Core.Entities.DocumentEngine.DocumentPage");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PageTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("HomePages");
                });

            modelBuilder.Entity("LumStoreAPI.Core.Entities.DocumentEngine.DocumentLinkedNode", b =>
                {
                    b.HasOne("LumStoreAPI.Core.Entities.DocumentEngine.DocumentNode", "AncestorNode")
                        .WithMany("AncestorNodes")
                        .HasForeignKey("Ancestor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LumStoreAPI.Core.Entities.DocumentEngine.DocumentNode", "DescendantNode")
                        .WithMany("DescendantNodes")
                        .HasForeignKey("Descendant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AncestorNode");

                    b.Navigation("DescendantNode");
                });

            modelBuilder.Entity("LumStoreAPI.Core.Entities.DocumentEngine.DocumentNode", b =>
                {
                    b.HasOne("LumStoreAPI.Core.Entities.DocumentEngine.DocumentNode", "Parent")
                        .WithMany("Childrens")
                        .HasForeignKey("ParentNodeID");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("LumStoreAPI.Core.Entities.DocumentEngine.DocumentPage", b =>
                {
                    b.HasOne("LumStoreAPI.Core.Entities.DocumentEngine.DocumentNode", "Node")
                        .WithMany("Properties")
                        .HasForeignKey("NodeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");
                });

            modelBuilder.Entity("LumStoreAPI.Core.Entities.Systems.MediaLibrary", b =>
                {
                    b.HasOne("LumStoreAPI.Core.Entities.Systems.MediaLibraryCategory", "MediaLibraryCategory")
                        .WithMany("MediaLibraries")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaLibraryCategory");
                });

            modelBuilder.Entity("LumStoreAPI.Core.Entities.HomePage", b =>
                {
                    b.HasOne("LumStoreAPI.Core.Entities.DocumentEngine.DocumentPage", null)
                        .WithOne()
                        .HasForeignKey("LumStoreAPI.Core.Entities.HomePage", "PageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LumStoreAPI.Core.Entities.DocumentEngine.DocumentNode", b =>
                {
                    b.Navigation("AncestorNodes");

                    b.Navigation("Childrens");

                    b.Navigation("DescendantNodes");

                    b.Navigation("Properties");
                });

            modelBuilder.Entity("LumStoreAPI.Core.Entities.Systems.MediaLibraryCategory", b =>
                {
                    b.Navigation("MediaLibraries");
                });
#pragma warning restore 612, 618
        }
    }
}
